version: '3.8'

services:
  # MongoDB must be a replica set for transactions (and many other db features) to work:
  mongodb:
    image: mongo:7.0
    command: ['--replSet', 'rs0', '--bind_ip_all', '--port', '27017']
    environment:
      MONGO_INITDB_DATABASE: mydb
    ports:
      - 27017:27017
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - 'mongodb_data:/data/db'
      - 'mongodb_config:/data/configdb'

volumes:
  mongodb_data:
  mongodb_config:
